package com.sociodyne.validation.edi;

public interface EdiConstants {

	/** Namespace of elements generated by the reader. */
	public static final String NAMESPACE_URI = "http://www.sociodyne.com/xmlns/edi";

}
