package com.sociodyne.validation.edi;

public interface EdiConstants {
	/** Namespace for the {@code xml:} namespace prefix. */
	static final String XML_NAMESPACE_URI = "http://www.w3.org/XML/1998/namespace";

	/** Namespace of elements generated by the reader. */
	static final String NAMESPACE_URI = "http://www.sociodyne.com/xmlns/edi";

}
